listener 1883 0.0.0.0

allow_anonymous false

password_file /home/srcds/crosschat_mqtt/mosquitto/passwd
acl_file /home/srcds/crosschat_mqtt/mosquitto/aclfile

persistence true
persistence_location /home/srcds/crosschat_mqtt/mosquitto/

log_dest stderr
log_type error
log_type warning
log_type notice
log_type information

connection_messages true
